# Generated by Django 5.1.4 on 2025-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0002_alter_teammember_role_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
